version: '3'
 
services:
  app1:
    build:
      context:  ./app
    expose:
      - "5000"
  app2:
    build:
      context:  ./app
    expose:
      - "5000"
  app3:
    build:
      context:  ./app
    expose:
      - "5000"
 
  proxy:
    build:
      context:  ./nginx
    ports:
      - "80:80"
    links:
      - app1
      - app2
      - app3